version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.24"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - nakedret
    - revive
    - staticcheck
    - unused

  settings:
    nakedret:
      # Aggressively disallow naked returns
      max-func-lines: 3

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
